using System;
using System.Linq;
using Standard.Licensing;
using Standard.Licensing.Validation;
using ThriveERP.Application.Common.Interfaces;
using ThriveERP.Infrastructure.Data;

namespace ThriveERP.Infrastructure.Services
{
    public class LicenseService : ILicenseService
    {
        private readonly ThriveErpDbContext _dbContext;

        // The Public Key used to verify the license was signed by YOU.
        // Replace this with the content of public_key.xml generated by ThriveERP.LicenseGenerator!
        private const string PublicKey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEob8NPgwHAikAUAMueIbTvRLej1qdqmzk229QlBeGYNdWD3tIU3O1BQtFaawx0Nl0f13AGFWGdjjItrFtOOHM8g==";

        public LicenseService(ThriveErpDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public bool IsLicenseValid(string licenseKey)
        {
            return ValidateLicense(licenseKey).IsValid;
        }

        public int GetDaysRemaining(string licenseKey)
        {
            var result = ValidateLicense(licenseKey);
            if (!result.IsValid || result.ExpirationDate == null)
                return 0;

            var timeRemaining = result.ExpirationDate.Value - DateTime.UtcNow;
            return timeRemaining.TotalDays > 0 ? (int)timeRemaining.TotalDays : 0;
        }

        public (bool IsValid, DateTime? ExpirationDate, string? CustomerName, string? ErrorMessage) ValidateLicense(string licenseKey)
        {
            if (string.IsNullOrWhiteSpace(licenseKey))
                return (false, null, null, "License key is empty.");

            try
            {
                var license = License.Load(licenseKey);

                // 1. Verify Signature
                var validationFailures = license.Validate()
                    .ExpirationDate()
                    .When(lic => lic.Type == LicenseType.Standard)
                    .And()
                    .Signature(PublicKey)
                    .AssertValidLicense();

                if (validationFailures.Any())
                {
                    var error = validationFailures.First().Message;
                    return (false, null, null, $"License Validation Failed: {error}");
                }

                // 2. Anti-Time-Travel Check (Offline protection)
                // Check if the system clock has been tampered with (moved backwards).
                // We do this by checking the newest record in the database.
                if (IsSystemClockTampered())
                {
                    return (false, null, null, "System clock tampering detected. Please ensure your computer's date and time are correct.");
                }

                return (true, license.Expiration, license.Customer?.Name, null);
            }
            catch (Exception)
            {
                return (false, null, null, "Invalid license format.");
            }
        }

        private bool IsSystemClockTampered()
        {
            try
            {
                // Find the newest SalesOrder as a reference for the actual time
                var newestOrder = _dbContext.SalesOrders
                    .OrderByDescending(x => x.OrderDate)
                    .FirstOrDefault();

                if (newestOrder != null)
                {
                    // If the current system time is BEFORE the newest order was created,
                    // it means the user changed their computer's calendar to the past!
                    if (DateTime.UtcNow < newestOrder.OrderDate.AddMinutes(-5)) // 5 min buffer
                    {
                        return true; 
                    }
                }
            }
            catch 
            {
                // If DB check fails for some reason, we assume it's okay to avoid hard locking
            }
            
            return false;
        }
    }
}
